name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Generate Configuration
        run: |
          mkdir build
          cmake -S . -B build
      - name: Build
        run: |
          cmake --build build --config Release
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: WindowsBinary
          path: build\Release\inventoryMonteCarlo.exe
      - name: Upload Release Assets
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: daily
          file: build\Release\inventoryMonteCarlo.exe
          asset_name: inventoryMonteCarlo.exe
          overwrite: true
